// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Commentary struct {
	ID          int64
	Scope       string
	ScopeID     int64
	Content     string
	GeneratedAt time.Time
}

type Course struct {
	ID        int64
	Name      string
	GolfApiID sql.NullString
	CreatedAt time.Time
}

type CourseHole struct {
	ID             int64
	CourseID       int64
	HoleNumber     int64
	GreenCentreLat sql.NullFloat64
	GreenCentreLng sql.NullFloat64
}

type Hole struct {
	ID           int64
	RoundID      int64
	CourseHoleID int64
	HoleNumber   int64
	FlagPosition sql.NullString
	Score        sql.NullInt64
	Points       sql.NullInt64
	Putts        sql.NullInt64
	FairwayHit   sql.NullBool
	Gir          sql.NullBool
	ScrambleSave sql.NullBool
	Penalty      sql.NullBool
}

type HolePointsOfInterest struct {
	ID             int64
	CourseHoleID   int64
	SpecificTee    sql.NullString
	PoiType        string
	Side           sql.NullString
	ReferencePoint sql.NullString
	DistanceStart  sql.NullFloat64
	DistanceEnd    sql.NullFloat64
	Label          string
}

type Player struct {
	ID        int64
	Name      string
	Handicap  sql.NullFloat64
	UpdatedAt time.Time
}

type PlayerClub struct {
	ID             int64
	PlayerID       int64
	ClubName       string
	AddedDate      time.Time
	RemovedDate    sql.NullTime
	CarryAvg       sql.NullFloat64
	CarryReliable  sql.NullFloat64
	CarryMax       sql.NullFloat64
	DispersionAvgM sql.NullFloat64
	DispersionBias sql.NullString
	SampleSize     int64
	CalculatedAt   sql.NullTime
}

type Round struct {
	ID              int64
	PlayerID        int64
	CourseID        int64
	PlayedAt        time.Time
	DailyHandicap   int64
	Tees            string
	RoundType       string
	CompetitionType sql.NullString
	TotalScore      sql.NullInt64
	TotalPoints     sql.NullInt64
	TotalPutts      sql.NullInt64
	CreatedAt       time.Time
}

type Shot struct {
	ID                    int64
	HoleID                int64
	ShotNumber            int64
	ShotType              string
	Club                  sql.NullString
	Result                sql.NullString
	Miss                  sql.NullString
	StrikeQuality         sql.NullString
	PreShotRecommendation sql.NullString
	Source                string
}

type Tee struct {
	ID           int64
	CourseID     int64
	Name         string
	SlopeRating  sql.NullInt64
	CourseRating sql.NullFloat64
}

type TeeHole struct {
	ID           int64
	CourseHoleID int64
	TeeID        int64
	Par          int64
	StrokeIndex  sql.NullInt64
	Distance     int64
	TeeCentreLat sql.NullFloat64
	TeeCentreLng sql.NullFloat64
}

type Vocabulary struct {
	Domain    string
	Value     string
	Label     string
	SortOrder int64
}
