// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const getClubDistances = `-- name: GetClubDistances :many
SELECT p.Id, p.Name, pc.club_name, pc.carry_avg, pc.carry_reliable, pc.carry_max, pc.dispersion_avg_m, pc.dispersion_bias FROM players p INNER JOIN player_clubs pc ON p.id = pc.player_id WHERE p.Name = ?
`

type GetClubDistancesRow struct {
	ID             int64
	Name           string
	ClubName       string
	CarryAvg       sql.NullFloat64
	CarryReliable  sql.NullFloat64
	CarryMax       sql.NullFloat64
	DispersionAvgM sql.NullFloat64
	DispersionBias sql.NullString
}

func (q *Queries) GetClubDistances(ctx context.Context, name string) ([]GetClubDistancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getClubDistances, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClubDistancesRow
	for rows.Next() {
		var i GetClubDistancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClubName,
			&i.CarryAvg,
			&i.CarryReliable,
			&i.CarryMax,
			&i.DispersionAvgM,
			&i.DispersionBias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseByName = `-- name: GetCourseByName :one
SELECT id, name, golf_api_id, created_at FROM courses WHERE name = ?
`

func (q *Queries) GetCourseByName(ctx context.Context, name string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByName, name)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GolfApiID,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerById = `-- name: GetPlayerById :one
SELECT id, name, handicap, updated_at from players WHERE id = ?
`

func (q *Queries) GetPlayerById(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerById, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handicap,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByName = `-- name: GetPlayerByName :one
SELECT id, name, handicap, updated_at 
from players p 
WHERE p.name=?
`

func (q *Queries) GetPlayerByName(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByName, name)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Handicap,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeesByCourse = `-- name: GetTeesByCourse :many
SELECT ct.id, ct.name, ct.slope_rating, ct.course_rating FROM tees ct WHERE course_id=?
`

type GetTeesByCourseRow struct {
	ID           int64
	Name         string
	SlopeRating  sql.NullInt64
	CourseRating sql.NullFloat64
}

func (q *Queries) GetTeesByCourse(ctx context.Context, courseID int64) ([]GetTeesByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeesByCourseRow
	for rows.Next() {
		var i GetTeesByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SlopeRating,
			&i.CourseRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, handicap, updated_at 
FROM players
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handicap,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
